dist: xenial
language: python
python:
- '3.7'

install:
- pip install -r requirements.txt

script: pytest

deploy:
  provider: gae
  keyfile: client-secret.json
  project: rss-aggregator-236618
before_install:
- openssl aes-256-cbc -K $encrypted_290a4f8623c5_key -iv $encrypted_290a4f8623c5_iv
  -in client-secret.json.enc -out client-secret.json -d
