dist: xenial
language: python
python:
- '3.7'

install:
- pip install -r requirements.txt
- (cd frontend && npm ci)

script:
  - pytest tests
  - (cd frontend && npm run-script build && mv build ../static )

deploy:
  - provider: gae
    keyfile: client-secret.json
    project: rss-aggregator-236707
    version: $version
    verbosity: info
  - provider: gae
    keyfile: client-secret.json
    project: rss-aggregator-236707
    version: $version
    config: cron.yaml

before_install:
- openssl aes-256-cbc -K $encrypted_290a4f8623c5_key -iv $encrypted_290a4f8623c5_iv
  -in client-secret.json.enc -out client-secret.json -d
- export version="develop-$(git log | wc -l)"
- echo $version

before_deploy:
  - find static