dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- "(cd frontend && npm ci)"
script:
- pytest tests --cov . --cov-report=html --cov-report=xml:build-reports/coverage.xml
- "(cd frontend && ./deploy.sh )"
- ./run-integration-test.sh
- pylint main.py app/**
- mypy main.py

deploy:
- provider: gae
  keyfile: travis-deployer.json
  project: rss-aggregator-236707
  version: "$version"
  verbosity: debug
  skip_cleanup: true
  config: app.yaml
- provider: gae
  keyfile: travis-deployer.json
  project: rss-aggregator-236707
  version: "$version"
  config: cron.yaml

before_install:
- sudo apt-get update
- sudo apt-get install language-pack-nl
- openssl aes-256-cbc -K $encrypted_290a4f8623c5_key -iv $encrypted_290a4f8623c5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xf secrets.tar
- export version="develop-`git rev-parse --short HEAD`"
- echo $version
