runtime: python37

handlers:
- url: ('/')
  static_files: static/build/index.html
  upload: static/build/index.html

- url: /static/css/(.*\.css)$
  static_files: static/build/static/css/\1
  upload: static/build/static/css/.*\.css$

- url: /static/js/(.*\.js)$
  static_files: static/build/static/js/\1
  upload: static/build/static/css/.*\.(css|map)$

- url: /(.*\.(json|png|ico|html|js))$
  static_files: static/build/\1
  upload: static/build/.*\.(json|png|ico|html|js)$
